problem:
  stack-trace: false
micronaut:
  application:
    name: oda-tribute-service
  serde:
    serialization:
      inclusion: ALWAYS
  security:
    token:
      bearer:
        enabled: true
      cookie:
        enabled: false
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
  executors:
    event-listener:
      type: fixed
      nThreads: 1
endpoints:
  prometheus:
    sensitive: false
  metrics:
    sensitive: false
flyway:
  datasources:
    default:
      enabled: true
